export const GET_DAILY_SUDOKU_LIST = 'GET_DAILY_SUDOKU_LIST';
export const GET_DAILY_SUDOKU_LIST_SUCCESS = 'GET_DAILY_SUDOKU_LIST_SUCCESS';

export const GET_DAILY_SUDOKU = 'GET_DAILY_SUDOKU';
export const GET_DAILY_SUDOKU_SUCCESS = 'GET_DAILY_SUDOKU_SUCCESS';
export const UPDATE_DAILY_SUDOKU = 'UPDATE_DAILY_SUDOKU';
export const POST_DAILY_SUDOKU_SCORE = 'POST_DAILY_SUDOKU_SCORE';

export const SUBMIT_REGISTER_USER = 'SUBMIT_REGISTER_USER';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';